from ROOT import TFile, TCanvas, TH2D, TH2, gStyle

#f = TFile("comparisonTree_040319_anglesAt001.root","READ")
f = TFile("output/protonAll.root","READ")
t = f.Get("tree")

c1 = TCanvas("canvas", "canvas", 720, 152, 682, 505)
c1.cd()
corr = TH2D("corr","Chosen X vs. Input X",100,0,260,100,0,260)
f.tree.Draw("chosenX:x>>corr", "", "COLZ")
corr.GetXaxis().SetTitle("Input X [cm]")
corr.GetYaxis().SetTitle("Chosen X [cm]")
corr.GetXaxis().SetTitleSize(0.05)
corr.GetXaxis().SetTitleOffset(0.9)
corr.GetYaxis().SetTitleSize(0.05)
corr.GetYaxis().SetTitleOffset(0.9)
corr.SetStats(0)
gStyle.SetTitleSize(0.07,"t")

input = raw_input("Press enter to continue...")

c2 = TCanvas("canvas", "canvas", 720, 152, 682, 505)
c2.cd()
corr = TH2D("corr","Chosen Y vs. Input Y",100,-115,115,100,-115,115)
f.tree.Draw("chosenY:y>>corr", "", "COLZ")
corr.GetXaxis().SetTitle("Input Y [cm]")
corr.GetYaxis().SetTitle("Chosen Y [cm]")
corr.GetXaxis().SetTitleSize(0.05)
corr.GetXaxis().SetTitleOffset(0.9)
corr.GetYaxis().SetTitleSize(0.05)
corr.GetYaxis().SetTitleOffset(0.9)
corr.SetStats(0)
gStyle.SetTitleSize(0.07,"t")

input = raw_input("Press enter to continue...")

c3 = TCanvas("canvas", "canvas", 720, 152, 682, 505)
c3.cd()
corr = TH2D("corr","Chosen Z vs. Input Z",100,-100,1100,100,-100,1100)
f.tree.Draw("chosenZ:z>>corr", "", "COLZ")
corr.GetXaxis().SetTitle("Input Z [cm]")
corr.GetYaxis().SetTitle("Chosen Z [cm]")
corr.GetXaxis().SetTitleSize(0.05)
corr.GetXaxis().SetTitleOffset(0.9)
corr.GetYaxis().SetTitleSize(0.05)
corr.GetYaxis().SetTitleOffset(0.9)
corr.SetStats(0)
gStyle.SetTitleSize(0.07,"t")

input = raw_input("Press enter to continue...")

c4 = TCanvas("canvas", "canvas", 720, 152, 682, 505)
c4.cd()
corr = TH2D("corr","Chosen pTheta vs. Input pTheta",100,0,3.1,100,0,3.1)
f.tree.Draw("chosenPTheta:pTheta>>corr", "", "COLZ")
corr.GetXaxis().SetTitle("Input Proton Theta Angle [radians]")
corr.GetYaxis().SetTitle("Chosen Proton Theta Angle [radians]")
corr.GetXaxis().SetTitleSize(0.05)
corr.GetXaxis().SetTitleOffset(0.9)
corr.GetYaxis().SetTitleSize(0.05)
corr.GetYaxis().SetTitleOffset(0.9)
corr.SetStats(0)
gStyle.SetTitleSize(0.07,"t")

input = raw_input("Press enter to continue...")

c5 = TCanvas("canvas", "canvas", 720, 152, 682, 505)
c5.cd()
corr = TH2D("corr","Chosen pPhi vs. Input pPhi",100,-4,4,100,-4,4)
f.tree.Draw("chosenPPhi:pPhi>>corr", "", "COLZ")
corr.GetXaxis().SetTitle("Input Proton Phi Angle [radians]")
corr.GetYaxis().SetTitle("Chosen Proton Phi Angle [radians]")
corr.GetXaxis().SetTitleSize(0.05)
corr.GetXaxis().SetTitleOffset(0.9)
corr.GetYaxis().SetTitleSize(0.05)
corr.GetYaxis().SetTitleOffset(0.9)
corr.SetStats(0)
gStyle.SetTitleSize(0.07,"t")

input = raw_input("Press enter to continue...")

c6 = TCanvas("canvas", "canvas", 720, 152, 682, 505)
c6.cd()
corr = TH2D("corr","Chosen pLen vs. Input pLen",100,0,250,100,0,250)
f.tree.Draw("chosenPLen:pLen>>corr", "", "COLZ")
corr.GetXaxis().SetTitle("Input Proton Length [cm]")
corr.GetYaxis().SetTitle("Chosen Proton Length [cm]")
corr.GetXaxis().SetTitleSize(0.05)
corr.GetXaxis().SetTitleOffset(0.9)
corr.GetYaxis().SetTitleSize(0.05)
corr.GetYaxis().SetTitleOffset(0.9)
corr.SetStats(0)
gStyle.SetTitleSize(0.07,"t")

input = raw_input("Press enter to continue...")

"""
c3 = TCanvas("canvas", "canvas", 720, 152, 682, 505)
c3.cd()
corr = TH2D("corr","Chosen pPhi vs. Input muPhi",100,-4,4,100,-4,4)
f.tree.Draw("chosenMuPhi:muPhi>>corr", "", "COLZ")
corr.GetXaxis().SetTitle("Input Proton Phi Angle [radians]")
corr.GetYaxis().SetTitle("Chosen Muon Phi Angle [radians]")

c4 = TCanvas("canvas", "canvas", 720, 152, 682, 505)
c4.cd()
corr = TH2D("corr","Chosen muPhi vs. Input muPhi",100,-4,4,100,-4,4)
f.tree.Draw("chosenMuPhi:muPhi>>corr", "", "COLZ")
corr.GetXaxis().SetTitle("Input Muon Phi Angle [radians]")
corr.GetYaxis().SetTitle("Chosen Muon Phi Angle [radians]")

c5 = TCanvas("canvas", "canvas", 720, 152, 682, 505)
c5.cd()
corr = TH2D("corr","Chosen muPhi vs. Input muPhi",100,-4,4,100,-4,4)
f.tree.Draw("chosenMuPhi:muPhi>>corr", "", "COLZ")
corr.GetXaxis().SetTitle("Input Muon Phi Angle [radians]")
corr.GetYaxis().SetTitle("Chosen Muon Phi Angle [radians]")

c6 = TCanvas("canvas", "canvas", 720, 152, 682, 505)
c6.cd()
corr = TH2D("corr","Chosen muPhi vs. Input muPhi",100,-4,4,100,-4,4)
f.tree.Draw("chosenMuPhi:muPhi>>corr", "", "COLZ")
corr.GetXaxis().SetTitle("Input Muon Phi Angle [radians]")
corr.GetYaxis().SetTitle("Chosen Muon Phi Angle [radians]")

"""
